### PR TITLE
Demo GitHub Flow

### PR DESCRIPTION
**Pull request by dfoll**
@jaw6 @mfunk This .md file was created as part of learning how to create a good commit message. Thoughts?
### TODO LIST
- [ ] get some feedback
- [ ] add some content

_hear is some italic text_
**hear is some bold text**

 Henry Rollins said 

> Two hundred pounds is always two hundred pounds

### CODE REVIEW

**Comment by dfoll** [comment]
I think i properly commented on #1

**Comment by mdwonchidt911** [comment]
comment on #1

**Comment by topowright-zz** [comment]
Just about write , wright or right

**Comment by mfunk** [comment]
Yup.... got it.

**Pull request merged**
